-- Insert test analytics data for saved_readings
-- This script creates diverse readings throughout 2025 for testing the analytics dashboard

-- First, get the user ID (replace with your actual user ID)
-- You can find this by running: SELECT id FROM auth.users LIMIT 1;

-- Sample readings with various characteristics
INSERT INTO public.saved_readings (
  user_id,
  title,
  question,
  spread_type,
  cards,
  interpretation,
  notes,
  is_public,
  created_at,
  accuracy_rating,
  sentiment,
  outcome_notes,
  reviewed_at,
  power_score,
  major_arcana_count,
  court_card_count,
  suit_pattern_score,
  reversal_percentage,
  tags
) VALUES
-- January readings (Winter Solstice period)
(
  (SELECT id FROM auth.users LIMIT 1),
  'New Year Intentions',
  'What energy should I focus on this year?',
  'three-card',
  '[{"card": {"name": "The Fool", "arcana": "major"}, "position": "Past", "isReversed": false}, {"card": {"name": "The Star", "arcana": "major"}, "position": "Present", "isReversed": false}, {"card": {"name": "Ace of Spring", "arcana": "minor", "suit": "spring"}, "position": "Future", "isReversed": false}]'::jsonb,
  'A powerful reading showing new beginnings and hope.',
  'Felt very aligned with my intentions',
  false,
  '2025-01-05 10:30:00+00',
  5,
  'positive',
  'This reading proved incredibly accurate - I started a new creative project in spring',
  '2025-03-15 14:20:00+00',
  85,
  2,
  0,
  0,
  0,
  ARRAY['new-year', 'intentions', 'powerful']
),
-- February reading (Imbolc)
(
  (SELECT id FROM auth.users LIMIT 1),
  'Career Decision',
  'Should I accept the new job offer?',
  'celtic-cross',
  '[{"card": {"name": "The Emperor", "arcana": "major"}, "position": "Present", "isReversed": false}, {"card": {"name": "King of Autumn", "arcana": "minor", "suit": "autumn"}, "position": "Advice", "isReversed": false}, {"card": {"name": "Ten of Pentacles", "arcana": "minor", "suit": "pentacles"}, "position": "Outcome", "isReversed": false}, {"card": {"name": "Three of Cups", "arcana": "minor", "suit": "cups"}, "position": "Challenge", "isReversed": true}]'::jsonb,
  'Strong indicators of career advancement and material success.',
  'The reversed Three of Cups warned about leaving my team',
  true,
  '2025-02-02 16:45:00+00',
  4,
  'positive',
  'Took the job - it worked out well!',
  '2025-04-10 09:00:00+00',
  75,
  1,
  1,
  0,
  25,
  ARRAY['career', 'decision', 'imbolc']
),
-- March reading (Spring Equinox)
(
  (SELECT id FROM auth.users LIMIT 1),
  'Spring Equinox Balance',
  'Where do I need more balance?',
  'three-card',
  '[{"card": {"name": "Justice", "arcana": "major"}, "position": "Past", "isReversed": false}, {"card": {"name": "Two of Pentacles", "arcana": "minor", "suit": "pentacles"}, "position": "Present", "isReversed": true}, {"card": {"name": "Temperance", "arcana": "major"}, "position": "Future", "isReversed": false}]'::jsonb,
  'Strong message about finding equilibrium in work-life balance.',
  'Need to be more mindful',
  false,
  '2025-03-20 07:15:00+00',
  5,
  'neutral',
  'The reversed Two of Pentacles was spot on - I was juggling too much',
  '2025-05-01 11:30:00+00',
  90,
  3,
  0,
  0,
  33.33,
  ARRAY['balance', 'equinox', 'spring']
),
-- April reading
(
  (SELECT id FROM auth.users LIMIT 1),
  'Relationship Check-in',
  'What does my relationship need right now?',
  'three-card',
  '[{"card": {"name": "The Lovers", "arcana": "major"}, "position": "Past", "isReversed": false}, {"card": {"name": "Queen of Cups", "arcana": "minor", "suit": "cups"}, "position": "Present", "isReversed": false}, {"card": {"name": "Four of Wands", "arcana": "minor", "suit": "wands"}, "position": "Future", "isReversed": false}]'::jsonb,
  'Beautiful reading showing deep emotional connection and celebration ahead.',
  'Planning an anniversary celebration',
  false,
  '2025-04-12 19:20:00+00',
  5,
  'positive',
  'We had a wonderful celebration exactly as predicted',
  '2025-05-20 16:00:00+00',
  70,
  1,
  1,
  0,
  0,
  ARRAY['love', 'relationship', 'celebration']
),
-- May reading (Beltane)
(
  (SELECT id FROM auth.users LIMIT 1),
  'Beltane Abundance',
  'What is growing in my life?',
  'single',
  '[{"card": {"name": "Ace of Pentacles", "arcana": "minor", "suit": "pentacles"}, "position": "Single", "isReversed": false}]'::jsonb,
  'New financial opportunity emerging.',
  'Exciting!',
  true,
  '2025-05-01 08:00:00+00',
  4,
  'positive',
  'Got a bonus at work',
  '2025-06-01 10:00:00+00',
  45,
  0,
  0,
  0,
  0,
  ARRAY['beltane', 'abundance', 'prosperity']
),
-- June reading (Summer Solstice)
(
  (SELECT id FROM auth.users LIMIT 1),
  'Summer Solstice Peak',
  'What is at its peak in my life?',
  'three-card',
  '[{"card": {"name": "The Sun", "arcana": "major"}, "position": "Past", "isReversed": false}, {"card": {"name": "Nine of Cups", "arcana": "minor", "suit": "cups"}, "position": "Present", "isReversed": false}, {"card": {"name": "The World", "arcana": "major"}, "position": "Future", "isReversed": false}]'::jsonb,
  'Incredibly positive reading showing achievement and fulfillment.',
  'Best reading ever!',
  false,
  '2025-06-21 12:00:00+00',
  5,
  'positive',
  'Everything came together beautifully',
  '2025-08-15 14:00:00+00',
  95,
  3,
  0,
  0,
  0,
  ARRAY['solstice', 'summer', 'success', 'peak']
),
-- July reading
(
  (SELECT id FROM auth.users LIMIT 1),
  'Creative Project Guidance',
  'How should I approach my creative work?',
  'three-card',
  '[{"card": {"name": "The Magician", "arcana": "major"}, "position": "Past", "isReversed": false}, {"card": {"name": "Three of Wands", "arcana": "minor", "suit": "wands"}, "position": "Present", "isReversed": false}, {"card": {"name": "Page of Wands", "arcana": "minor", "suit": "wands"}, "position": "Future", "isReversed": false}]'::jsonb,
  'Strong fire energy showing creative expansion and new ideas.',
  'Lots of wands!',
  false,
  '2025-07-10 15:30:00+00',
  4,
  'positive',
  'Started three new creative projects',
  '2025-09-01 11:00:00+00',
  80,
  1,
  1,
  15,
  0,
  ARRAY['creativity', 'fire', 'inspiration']
),
-- August reading (Lughnasadh)
(
  (SELECT id FROM auth.users LIMIT 1),
  'First Harvest',
  'What am I harvesting from my efforts?',
  'three-card',
  '[{"card": {"name": "Seven of Pentacles", "arcana": "minor", "suit": "pentacles"}, "position": "Past", "isReversed": false}, {"card": {"name": "Nine of Pentacles", "arcana": "minor", "suit": "pentacles"}, "position": "Present", "isReversed": false}, {"card": {"name": "Ten of Pentacles", "arcana": "minor", "suit": "pentacles"}, "position": "Future", "isReversed": false}]'::jsonb,
  'Perfect harvest reading - three pentacles showing material growth.',
  'Pentacles trine is powerful',
  true,
  '2025-08-01 09:45:00+00',
  5,
  'positive',
  'Received recognition for my hard work',
  '2025-09-15 13:00:00+00',
  60,
  0,
  0,
  15,
  0,
  ARRAY['harvest', 'lughnasadh', 'reward', 'pentacles']
),
-- September reading (Autumn Equinox)
(
  (SELECT id FROM auth.users LIMIT 1),
  'Autumn Balance',
  'What should I release as we move into autumn?',
  'three-card',
  '[{"card": {"name": "Death", "arcana": "major"}, "position": "Past", "isReversed": false}, {"card": {"name": "Five of Cups", "arcana": "minor", "suit": "cups"}, "position": "Present", "isReversed": true}, {"card": {"name": "Eight of Swords", "arcana": "minor", "suit": "swords"}, "position": "Future", "isReversed": true}]'::jsonb,
  'Powerful transformation reading with reversals showing release.',
  'Letting go is hard but necessary',
  false,
  '2025-09-22 18:00:00+00',
  4,
  'neutral',
  'Successfully let go of old patterns',
  '2025-11-01 10:00:00+00',
  75,
  1,
  0,
  0,
  66.66,
  ARRAY['release', 'transformation', 'equinox', 'autumn']
),
-- October reading
(
  (SELECT id FROM auth.users LIMIT 1),
  'Shadow Work',
  'What shadow aspect needs my attention?',
  'single',
  '[{"card": {"name": "The Moon", "arcana": "major"}, "position": "Single", "isReversed": false}]'::jsonb,
  'Deep dive into subconscious patterns.',
  'Doing inner work',
  false,
  '2025-10-15 20:30:00+00',
  3,
  'neutral',
  'Still working on understanding the message',
  '2025-11-10 15:00:00+00',
  50,
  1,
  0,
  0,
  0,
  ARRAY['shadow-work', 'moon', 'introspection']
),
-- October (Samhain)
(
  (SELECT id FROM auth.users LIMIT 1),
  'Samhain Ancestors',
  'What wisdom do my ancestors offer?',
  'three-card',
  '[{"card": {"name": "The Hermit", "arcana": "major"}, "position": "Past", "isReversed": false}, {"card": {"name": "Six of Cups", "arcana": "minor", "suit": "cups"}, "position": "Present", "isReversed": false}, {"card": {"name": "Queen of Pentacles", "arcana": "minor", "suit": "pentacles"}, "position": "Future", "isReversed": false}]'::jsonb,
  'Ancestral wisdom about nurturing and grounding.',
  'Felt my grandmother''s presence',
  false,
  '2025-10-31 23:59:00+00',
  5,
  'positive',
  'Following ancestral wisdom has been healing',
  '2025-11-15 12:00:00+00',
  65,
  1,
  1,
  0,
  0,
  ARRAY['samhain', 'ancestors', 'wisdom']
),
-- November reading
(
  (SELECT id FROM auth.users LIMIT 1),
  'Difficult Decision',
  'How do I navigate this conflict?',
  'three-card',
  '[{"card": {"name": "Five of Swords", "arcana": "minor", "suit": "swords"}, "position": "Past", "isReversed": true}, {"card": {"name": "Two of Swords", "arcana": "minor", "suit": "swords"}, "position": "Present", "isReversed": false}, {"card": {"name": "Six of Swords", "arcana": "minor", "suit": "swords"}, "position": "Future", "isReversed": false}]'::jsonb,
  'Swords journey from conflict to resolution.',
  'Challenging but clear guidance',
  false,
  '2025-11-10 14:00:00+00',
  3,
  'negative',
  'The situation was difficult but I moved forward',
  NULL,
  55,
  0,
  0,
  15,
  33.33,
  ARRAY['conflict', 'decision', 'swords']
);

-- Show the inserted data
SELECT
  title,
  TO_CHAR(created_at, 'YYYY-MM-DD') as date,
  accuracy_rating,
  sentiment,
  power_score,
  tags
FROM public.saved_readings
ORDER BY created_at DESC
LIMIT 20;
